spring.application.name=SoftGuard

# MySQL 접속 정보
#spring.datasource.url=jdbc:mysql://localhost:3306/softguard_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=111111

#배포용
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

# Railway MySQL
spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:39852/railway?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=odbvXyqqVFBHpdWJwThKbgSCBvyklCsy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#server.port=${PORT:8080}
#
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/softguard_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
#
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:111111}


# JPA/Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#HyperClovaX
clova.api.key=${CLOVA_API_KEY:}
clova.api.url=https://clovastudio.stream.ntruss.com/v3/chat-completions/HCX-007

# AWS S3 설정
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}
cloud.aws.region.static=ap-northeast-2
cloud.aws.s3.bucket=softguard-videos

